# Runs the CI build every time someone pushes to a branch.

name: Build Branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: "Build"
        run: chmod 755 gradlew && ./gradlew build

      - name: "Publish"
        if: github.ref == 'refs/heads/release'
        run: chmod 755 gradlew && ./gradlew artifactoryPublish