# Runs the CI build every time someone pushes to a branch.

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout sources"
        uses: actions/checkout@v2

      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: "Build"
        run: chmod 755 gradlew && ./gradlew build

      - name: "Publish"
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        if: github.ref == 'refs/heads/release'
        run: chmod 755 gradlew && ./gradlew artifactoryPublish